/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDnaAuction,
  IDnaAuctionInterface,
} from "../../../contracts/DnaCollection.sol/IDnaAuction";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "nftContract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "startingPrice",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
    ],
    name: "createAuction",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDnaAuction__factory {
  static readonly abi = _abi;
  static createInterface(): IDnaAuctionInterface {
    return new Interface(_abi) as IDnaAuctionInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDnaAuction {
    return new Contract(address, _abi, runner) as unknown as IDnaAuction;
  }
}
