/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DnaCollection__factory } from "./DnaCollection__factory";
export { IDnaAuction__factory } from "./IDnaAuction__factory";
