/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as test from "./test";
export { DnaAuction__factory } from "./DnaAuction__factory";
export { DnaCollection__factory } from "./DnaCollection__factory";
